# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='\u90ae\u7bb1')),
                ('message', models.CharField(max_length=500, verbose_name='\u7559\u8a00\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7559\u8a00\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00\u4fe1\u606f',
            },
        ),
    ]
